### PR TITLE
Adding support for !armour and !noarmour

### PR DESCRIPTION
**Pull request by jgh713**
Adding !armour and !noarmour commands to allow disabling armour on a per-map basis on speedrun servers.

NB: This has _not been tested yet_

### CODE REVIEW

**Comment by RussianRonin** [comment]
Why not make this a standalone plugin? Would make it more usable for other servers if needed.

Also, possibly add a per team setting if you do make it standalone?

**Comment by jgh713** [comment]
Cause armour was already built into the speedrun plugin.

**Comment by RussianRonin** [comment]
Oh ok. Maybe something to think about in the future.

**Comment by jgh713** [comment]
Marking #26

**Pull request merged**
